"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup
from PyQt5.Qt import *

APP = ['main.py']
DATA_FILES = ['MyWidget']
OPTIONS = {'includes': ['sys', 'PyQt5.Qt']}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
